const SESSION_ID_LENGTH = 50;
const SESSION_RESET_TIME = 2*60*60*1000; // 2 hours in Miliseceonds
const SESSION_TIMEOUT_CHECK_INTERVALL = 5*60*1000 // 5 minutes in Miliseconds

module.exports = {
    SESSION_ID_LENGTH: SESSION_ID_LENGTH,
    SESSION_RESET_TIME: SESSION_RESET_TIME,
    SESSION_TIMEOUT_CHECK_INTERVALL: SESSION_TIMEOUT_CHECK_INTERVALL,
};
